### ISSUE TITLE
Pls. restore the old (rectangular) icons in the feed list view

### ISSUE THREAD

**Issue by Wikinaut** [AndroidMakesFun/SparseRssMod#1]
The circle-shaped icons in the feed list are disturbing many icons, which are not suited for such cropping (e.g. letters).

**Comment by AndroidMakesFun** [comment]
Hi,
Ok, hm, could You send me a Screenshot? Thanks.
Which device?

Greetings
Bernd

Am 09.02.2017 19:27 schrieb "Wikinaut" <notifications@github.com>:

**Comment by Wikinaut** [comment]
HUAWEI P8 Lite

**Comment by Wikinaut** [comment]
Don't "shape" the icons. Previous version was "prima"

**Comment by AndroidMakesFun** [comment]
hm, could You send me a Screenshot? Thanks.

2017-02-09 21:21 GMT+01:00 Wikinaut <notifications@github.com>:
