### ISSUE TITLE
Preview of a certain feed shows "null"

### ISSUE THREAD

**Issue by Wikinaut** [AndroidMakesFun/SparseRssMod#2]
Pls. check the feed http://www.berlin.de/polizei/presse-fahndung/_rss_presse.xml . It shows "null" in the preview.

**Comment by AndroidMakesFun** [comment]
Look at the Feed

item>
        <title>Von der Fahrbahn abgekommen</title>
        <description><![CDATA[]]></description>
    <link>http://www.berlin.de/polizei/polizeimeldungen/pressemitteilung.560185.php</link>
<guid>/polizei/polizeimeldungen/pressemitteilung.560185.php</guid>
        <pubDate>Sat, 11 Feb 2017 10:18:36 +0100</pubDate>
        <author>mailto:Views_Flex_Autoteaser_ListItem@localhost</author>
    </item>


Their is noch entry with

"<description>"


User the readability Menü to scrap the content from the Page.


Greetings
Bernd

Am 11.02.2017 5:39 nachm. schrieb "Wikinaut" <notifications@github.com>:

**Comment by Wikinaut** [comment]
Empty field should be sanitized by the app.

(two typos corrected)

**Comment by AndroidMakesFun** [comment]
Ach so, ja da hast du Recht. Ist der erste "leere" Feed, den ich sehe.
Kommt auf die todo Liste, Danke.

Greetings
Bernd

Am 11.02.2017 6:04 nachm. schrieb "Wikinaut" <notifications@github.com>:

**Comment by Wikinaut** [comment]
Bernd, bitte könntest Du das "null" Problem lösen ? Wäre nett. Den Polizeiticker-Feed brauche ich täglich, und dort sind (fast, aber nicht) alle Feeds so konstruiert, wie beschrieben.

**Comment by AndroidMakesFun** [comment]
Ups, Dachte das war gefixt.
Sory, Danke für die Erinnerung, ist im nächsten Update drin!
Gruß
Bernd


Am 26. März 2017 um 21:37 schrieb Wikinaut <notifications@github.com>:

**Comment by Wikinaut** [comment]
Bitte könntest Du das fixen, danke.

**Comment by AndroidMakesFun** [comment]
Hi,
das habe ich dir doch am 30.3. mit der Version 2.29 gefixt.
Habe den feed eben nochmal angelegt und aktualisiert. Keine Null Werte.
Weder per Feed, noch per readability noch per GoogleWeblight.
Welche Version benutzt du?

Greetings
Bernd

Am 17.10.2017 11:10 vorm. schrieb "Wikinaut" <notifications@github.com>:

**Comment by Wikinaut** [comment]
Ich habe hier 2.25, vermutlich, weil ich die build-Probleme habe.

**Comment by Wikinaut** [comment]
Könntest Du bei Google Play updaten, dann kann ich von dort updaten.

**Comment by AndroidMakesFun** [comment]
Hallo,
GooglePlay hat 2.29

Greetings
Bernd

Am 14.11.2017 12:20 nachm. schrieb "Wikinaut" <notifications@github.com>:

**Comment by Wikinaut** [comment]
Ich sehe immer noch nur die 2.25. 

Wann hast Du das zu Google hochgeladen? Manchmal dauert das ja eine Weile, bis die neue Version "sichtbar" ist.

**Comment by Wikinaut** [comment]
Siehe https://play.google.com/store/apps/details?id=de.bernd.shandschuh.sparserss => Ist immer noch auf 2.25.

**Comment by Wikinaut** [comment]
@AndroidMakesFun Wann updatest Du die Google Play Version, die ist immer noch auf 2.25.

**Comment by AndroidMakesFun** [comment]
Sorry, GooglePlay hat den Rollout des letzten Updates auf der Hälfte angehalten.
Mobil wurde mir die ganze Zeit schon 229 angezeigt. Deshalb konnte ich Dein Problem auch nicht nachvollziehen. Unter Windows sehe ich gerade, das da noch 225 steht.
Das war unerwartet.
Habe das eben nochmal überall angestossen und werde das morgen nochmal unter Windows prüfen.
Damit sollte 229 jetzt auch endlich bei Dir ankommen. Sorry.

Gruß
Bernd

**Comment by Wikinaut** [comment]
@AndroidMakesFun yes, now I can download the 2.29 from Google Play.

Problem with "null" is now solved, but should be "resolved" by then automatically forwarding to the final webpage.

Example: the http://www.berlin.de/polizei/presse-fahndung/_rss_presse.xml feed items. Clicking onto an item should (in case of empty contents) directly go to webpage (at least, as an user option).

**Comment by Wikinaut** [comment]
Never seen again. Closing.
