### ISSUE TITLE
 No resource found that matches the given name 'Theme.AppCompat.Light.NoActionBar'.

### ISSUE THREAD

**Issue by Wikinaut** [AndroidMakesFun/SparseRssMod#3]
Error:(3, -1) android-apt-compiler: [Sparse RSS] SparseRssMod/SparseRss/Sparse RSS/res/values/styles.xml:3:

error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.NoActionBar'.

etc.

in Android Studio. Can you help? Does it work for you?

**Comment by AndroidMakesFun** [comment]
Hi,
stelle gerade von Eclipse auf Android Studio um. Werde das hier noch
aktualisieren.

Greetings
Bernd

Am 18.10.2017 8:02 nachm. schrieb "Wikinaut" <notifications@github.com>:
